[2024-08-13T18:10:14.101+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:14.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:10:14.144+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:10:14.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:14.185+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:10:14.178+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:10:14.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:14.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.369 seconds
[2024-08-13T18:10:44.798+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:44.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:10:44.805+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:10:44.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:44.812+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:10:44.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:10:44.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:10:44.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.099 seconds
[2024-08-13T18:11:15.176+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:15.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:11:15.179+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:11:15.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:15.184+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:11:15.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:11:15.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:15.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.040 seconds
[2024-08-13T18:11:45.644+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:45.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:11:45.651+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:11:45.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:45.658+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:11:45.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:11:45.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:11:45.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.102 seconds
[2024-08-13T18:12:15.996+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:15.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:12:16.000+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:12:16.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:16.005+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:12:16.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:12:16.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:16.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.040 seconds
[2024-08-13T18:12:46.460+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:46.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:12:46.466+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:12:46.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:46.473+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:12:46.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:12:46.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:12:46.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-13T18:13:17.463+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:17.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:13:17.582+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:13:17.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:17.614+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:13:17.612+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:13:17.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:17.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.257 seconds
[2024-08-13T18:13:48.137+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:48.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:13:48.145+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:13:48.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:48.152+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:13:48.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:13:48.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:13:48.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-13T18:14:18.569+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:18.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:14:18.575+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:14:18.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:18.582+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:14:18.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:14:18.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:18.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-13T18:14:49.046+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:49.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:14:49.050+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:14:49.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:49.056+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:14:49.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:14:49.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:14:49.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.036 seconds
[2024-08-13T18:15:19.521+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:19.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:15:19.527+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:15:19.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:19.533+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:15:19.532+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:15:19.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:19.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.052 seconds
[2024-08-13T18:15:49.949+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:49.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:15:49.954+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:15:49.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:49.958+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:15:49.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:15:49.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:15:49.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.037 seconds
[2024-08-13T18:16:20.360+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:20.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:16:20.366+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:16:20.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:20.371+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:16:20.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:16:20.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:20.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
[2024-08-13T18:16:50.737+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:50.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:16:50.741+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:16:50.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:50.745+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:16:50.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:16:50.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:16:50.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.040 seconds
[2024-08-13T18:17:21.173+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:21.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:17:21.178+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:17:21.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:21.183+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:17:21.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:17:21.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:21.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2024-08-13T18:17:51.621+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:51.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:17:51.629+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:17:51.628+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:51.651+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:17:51.647+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:17:51.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:17:51.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.168 seconds
[2024-08-13T18:18:22.096+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:22.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:18:22.103+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:18:22.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:22.111+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:18:22.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:18:22.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:22.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2024-08-13T18:18:52.552+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:52.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:18:52.559+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:18:52.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:52.566+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:18:52.565+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:18:52.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:18:52.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-08-13T18:19:22.990+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:22.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:19:22.997+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:19:22.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:23.005+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:19:23.003+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:19:23.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:23.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2024-08-13T18:19:53.422+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:53.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:19:53.428+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:19:53.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:53.435+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:19:53.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:19:53.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:19:53.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2024-08-13T18:20:23.861+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:23.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:20:23.866+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:20:23.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:23.872+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:20:23.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:20:23.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:23.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.051 seconds
[2024-08-13T18:20:54.208+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:54.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:20:54.211+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:20:54.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:54.217+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:20:54.216+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:20:54.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:20:54.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.040 seconds
[2024-08-13T18:21:24.570+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:24.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:21:24.575+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:21:24.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:24.580+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:21:24.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:21:24.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:24.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.043 seconds
[2024-08-13T18:21:54.916+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:54.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:21:54.919+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:21:54.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:54.923+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:21:54.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:21:54.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:21:54.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.038 seconds
[2024-08-13T18:22:25.284+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:25.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:22:25.290+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:22:25.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:25.296+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:22:25.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:22:25.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:25.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2024-08-13T18:22:55.658+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:55.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:22:55.661+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:22:55.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:55.666+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:22:55.665+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:22:55.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:22:55.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.036 seconds
[2024-08-13T18:23:26.077+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:26.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:23:26.089+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:23:26.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:26.102+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:23:26.100+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:23:26.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:26.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.079 seconds
[2024-08-13T18:23:56.446+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:56.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:23:56.453+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:23:56.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:56.460+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:23:56.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:23:56.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:23:56.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2024-08-13T18:24:26.863+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:26.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:24:26.868+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:24:26.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:26.873+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:24:26.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:24:26.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:26.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.073 seconds
[2024-08-13T18:24:57.328+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:57.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:24:57.334+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:24:57.333+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:57.339+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:24:57.338+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:24:57.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:24:57.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
[2024-08-13T18:25:27.786+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:27.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:25:27.790+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:25:27.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:27.794+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:25:27.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:25:27.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:27.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.035 seconds
[2024-08-13T18:25:58.238+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:58.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:25:58.243+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:25:58.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:58.250+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:25:58.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:25:58.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:25:58.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.138 seconds
[2024-08-13T18:26:28.726+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:28.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:26:28.736+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:26:28.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:28.742+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:26:28.741+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:26:28.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:28.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.073 seconds
[2024-08-13T18:26:59.243+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:59.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:26:59.246+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:26:59.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:59.251+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:26:59.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:26:59.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:26:59.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.037 seconds
[2024-08-13T18:27:29.689+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:27:29.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:27:29.693+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:27:29.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:27:29.699+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:27:29.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:27:29.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:27:29.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.047 seconds
[2024-08-13T18:28:00.174+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:00.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:28:00.178+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:28:00.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:00.182+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:28:00.182+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:28:00.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:00.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.036 seconds
[2024-08-13T18:28:30.636+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:30.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:28:30.644+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:28:30.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:30.650+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:28:30.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:28:30.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:28:30.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-13T18:29:01.074+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:01.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:29:01.078+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:29:01.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:01.082+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:29:01.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:29:01.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:01.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.032 seconds
[2024-08-13T18:29:31.492+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:31.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:29:31.496+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:29:31.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:31.502+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:29:31.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:29:31.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:29:31.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.046 seconds
[2024-08-13T18:30:20.316+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:20.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:30:20.321+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:30:20.321+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:20.329+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:30:20.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:30:20.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:20.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-08-13T18:30:50.715+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:50.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:30:50.720+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:30:50.720+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:50.726+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:30:50.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:30:50.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:30:50.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.046 seconds
[2024-08-13T18:31:26.276+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:26.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:31:26.283+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:31:26.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:26.290+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:31:26.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:31:26.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:26.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.093 seconds
[2024-08-13T18:31:56.669+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:56.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:31:56.675+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:31:56.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:56.681+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:31:56.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:31:56.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:31:56.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2024-08-13T18:32:27.019+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:27.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:32:27.028+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:32:27.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:27.035+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:32:27.034+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:32:27.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:27.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.083 seconds
[2024-08-13T18:32:57.421+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:57.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:32:57.427+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:32:57.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:57.433+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:32:57.432+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:32:57.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:32:57.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2024-08-13T18:33:28.163+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:28.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:33:28.177+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:33:28.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:28.238+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:33:28.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:33:28.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:28.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.717 seconds
[2024-08-13T18:33:59.428+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:59.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:33:59.439+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:33:59.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:59.448+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:33:59.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:33:59.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:33:59.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.094 seconds
[2024-08-13T18:34:29.828+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:34:29.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:34:29.842+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:34:29.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:34:29.848+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:34:29.847+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:34:29.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:34:29.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2024-08-13T18:35:00.300+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:00.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:35:00.304+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:35:00.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:00.310+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:35:00.309+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:35:00.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:00.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.079 seconds
[2024-08-13T18:35:30.680+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:30.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:35:30.685+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:35:30.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:30.691+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:35:30.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:35:30.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:35:30.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2024-08-13T18:36:01.079+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:01.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:36:01.101+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:36:01.100+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:01.109+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:36:01.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:36:01.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:01.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.083 seconds
[2024-08-13T18:36:31.456+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:31.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:36:31.462+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:36:31.462+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:31.470+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:36:31.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:36:31.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:36:31.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.063 seconds
[2024-08-13T18:37:01.805+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:01.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:37:01.811+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:37:01.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:01.818+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:37:01.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:37:01.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:01.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2024-08-13T18:37:32.214+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:32.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:37:32.234+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:37:32.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:32.245+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:37:32.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:37:32.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:37:32.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2024-08-13T18:38:02.609+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:02.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:38:02.615+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:38:02.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:02.621+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:38:02.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:38:02.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:02.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-08-13T18:38:33.013+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:33.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:38:33.028+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:38:33.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:33.063+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:38:33.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:38:33.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:38:33.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.129 seconds
[2024-08-13T18:39:03.517+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:03.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:39:03.524+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:39:03.523+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:03.532+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:39:03.530+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:39:03.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:03.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2024-08-13T18:39:33.947+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:33.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:39:33.954+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:39:33.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:33.961+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:39:33.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:39:33.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:39:34.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.081 seconds
[2024-08-13T18:40:04.327+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:04.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:40:04.332+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:40:04.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:04.337+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:40:04.337+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:40:04.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:04.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.043 seconds
[2024-08-13T18:40:34.755+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:34.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:40:34.759+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:40:34.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:34.763+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:40:34.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:40:34.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:40:34.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.047 seconds
[2024-08-13T18:41:05.143+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:05.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:41:05.148+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:41:05.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:05.155+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:41:05.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:41:05.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:05.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2024-08-13T18:41:35.486+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:35.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:41:35.490+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:41:35.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:35.496+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:41:35.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:41:35.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:41:35.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2024-08-13T18:42:05.866+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:05.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:42:05.872+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:42:05.872+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:05.878+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:42:05.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:42:05.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:05.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2024-08-13T18:42:36.304+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:36.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:42:36.309+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:42:36.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:36.315+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:42:36.314+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:42:36.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:42:36.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-13T18:43:06.735+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:06.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:43:06.741+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:43:06.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:06.748+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:43:06.747+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:43:06.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:06.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.076 seconds
[2024-08-13T18:43:37.135+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:37.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:43:37.142+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:43:37.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:37.147+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:43:37.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:43:37.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:43:37.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2024-08-13T18:44:07.550+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:07.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:44:07.555+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:44:07.555+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:07.561+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:44:07.560+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:44:07.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:07.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.047 seconds
[2024-08-13T18:44:38.086+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:38.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:44:38.101+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:44:38.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:38.111+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:44:38.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:44:38.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:44:38.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.070 seconds
[2024-08-13T18:45:08.516+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:08.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:45:08.523+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:45:08.523+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:08.529+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:45:08.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:45:08.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:08.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2024-08-13T18:45:39.013+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:39.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:45:39.018+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:45:39.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:39.024+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:45:39.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:45:39.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:45:39.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-13T18:46:09.382+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:09.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:46:09.386+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:46:09.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:09.392+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:46:09.391+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:46:09.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:09.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2024-08-13T18:46:39.738+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:39.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:46:39.744+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:46:39.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:39.750+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:46:39.749+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:46:39.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:46:39.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.083 seconds
[2024-08-13T18:47:10.273+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:10.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:47:10.316+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:47:10.313+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:10.348+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:47:10.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:47:10.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:10.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.610 seconds
[2024-08-13T18:47:41.392+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:41.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:47:41.399+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:47:41.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:41.405+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:47:41.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:47:41.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:47:41.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2024-08-13T18:48:11.983+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:11.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:48:12.003+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:48:12.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:12.012+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:48:12.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:48:12.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:12.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.097 seconds
[2024-08-13T18:48:42.332+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:42.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:48:42.338+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:48:42.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:42.344+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:48:42.343+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:48:42.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:48:42.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2024-08-13T18:49:12.721+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:12.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:49:12.727+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:49:12.726+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:12.733+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:49:12.732+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:49:12.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:12.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2024-08-13T18:49:43.173+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:43.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:49:43.178+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:49:43.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:43.185+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:49:43.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:49:43.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:49:43.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
[2024-08-13T18:50:13.685+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:13.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:50:13.721+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:50:13.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:13.747+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:50:13.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:50:13.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:13.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.292 seconds
[2024-08-13T18:50:43.926+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:43.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:50:43.935+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:50:43.934+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:43.951+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:50:43.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:50:43.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:50:44.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.099 seconds
[2024-08-13T18:51:14.200+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:51:14.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:51:14.218+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:51:14.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:51:14.257+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:51:14.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:51:14.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:51:14.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.174 seconds
[2024-08-13T18:53:00.167+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:00.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:53:00.206+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:53:00.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:00.229+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:53:00.223+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:53:00.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:00.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.352 seconds
[2024-08-13T18:53:30.676+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:30.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:53:30.733+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:53:30.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:30.793+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:53:30.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:53:30.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:53:31.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.422 seconds
[2024-08-13T18:54:02.076+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:02.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:54:02.181+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:54:02.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:02.322+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:54:02.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:54:02.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:02.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.152 seconds
[2024-08-13T18:54:33.725+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:33.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:54:33.737+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:54:33.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:33.776+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:54:33.772+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:54:33.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:54:34.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.326 seconds
[2024-08-13T18:55:04.653+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:04.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:55:04.799+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:55:04.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:05.019+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:55:04.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:55:05.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:06.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.138 seconds
[2024-08-13T18:55:37.334+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:37.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:55:37.411+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:55:37.401+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:37.598+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:55:37.585+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:55:37.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:55:38.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.409 seconds
[2024-08-13T18:56:11.190+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:11.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:56:11.624+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:56:11.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:11.974+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:56:11.947+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:56:12.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:12.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.413 seconds
[2024-08-13T18:56:45.511+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:45.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:56:45.749+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:56:45.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:46.050+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:56:46.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:56:46.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:56:46.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.409 seconds
[2024-08-13T18:57:19.599+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:19.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:57:20.084+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:57:20.019+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:20.362+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:57:20.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:57:20.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:21.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.447 seconds
[2024-08-13T18:57:54.062+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:54.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:57:54.627+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:57:54.567+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:55.866+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:57:55.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:57:55.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:57:58.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 5.857 seconds
[2024-08-13T18:58:30.506+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:58:30.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:58:30.664+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:58:30.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:58:30.817+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:58:30.803+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:58:30.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:58:31.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.606 seconds
[2024-08-13T18:59:03.753+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:03.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:59:04.197+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:59:04.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:04.523+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:59:04.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:59:04.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:05.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.406 seconds
[2024-08-13T18:59:37.632+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:37.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T18:59:37.977+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:59:37.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:38.514+0000] {logging_mixin.py:188} INFO - [2024-08-13T18:59:38.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T18:59:38.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T18:59:39.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.575 seconds
[2024-08-13T19:00:11.066+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:11.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:00:11.216+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:00:11.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:11.479+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:00:11.448+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:00:11.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:12.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.073 seconds
[2024-08-13T19:00:45.635+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:45.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:00:46.035+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:00:45.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:46.585+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:00:46.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:00:46.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:00:48.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 3.332 seconds
[2024-08-13T19:01:20.784+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:01:20.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:01:21.196+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:01:21.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:01:21.472+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:01:21.451+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:01:21.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:01:23.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 3.622 seconds
[2024-08-13T19:01:55.780+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:01:55.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:01:56.304+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:01:56.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:01:57.540+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:01:57.386+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:01:57.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:02:00.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 5.241 seconds
[2024-08-13T19:02:33.939+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:02:34.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:02:34.424+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:02:34.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:02:35.287+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:02:35.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:02:35.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:02:38.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 5.460 seconds
[2024-08-13T19:03:11.100+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:11.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:03:12.117+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:03:12.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:12.707+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:03:12.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:03:12.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:15.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 4.711 seconds
[2024-08-13T19:03:46.926+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:46.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:03:47.038+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:03:47.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:47.279+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:03:47.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:03:47.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:03:48.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.808 seconds
[2024-08-13T19:04:19.156+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:19.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:04:19.190+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:04:19.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:19.234+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:04:19.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:04:19.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:19.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.666 seconds
[2024-08-13T19:04:50.567+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:50.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:04:50.615+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:04:50.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:50.675+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:04:50.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:04:50.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:04:51.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.635 seconds
[2024-08-13T19:05:21.714+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:05:21.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:05:21.743+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:05:21.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:05:21.768+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:05:21.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:05:21.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:05:21.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.312 seconds
[2024-08-13T19:05:59.259+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:05:59.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:05:59.517+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:05:59.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:05:59.645+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:05:59.627+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:05:59.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:06:00.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.728 seconds
[2024-08-13T19:06:32.038+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:06:32.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:06:32.553+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:06:32.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:06:32.701+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:06:32.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:06:32.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:06:33.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.006 seconds
[2024-08-13T19:07:05.212+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:05.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:07:05.458+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:07:05.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:05.556+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:07:05.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:07:05.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:06.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.405 seconds
[2024-08-13T19:07:37.452+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:37.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-13T19:07:37.721+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:07:37.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:38.097+0000] {logging_mixin.py:188} INFO - [2024-08-13T19:07:38.062+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index:0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                           ^
SyntaxError: invalid syntax
[2024-08-13T19:07:38.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-13T19:07:38.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.696 seconds
